os: osx
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8
script:
  - "brew update"
  - "brew install pyenv"
  - "pyenv"
  - "pyenv install 3.5.2"
  - "pyenv local 3.5.2"
  - "pip install --upgrade pip"
  - "pip --version"
  - "pip install socialreaper pyqt5 pyinstaller"
  - "pyinstaller -y --windowed --icon=ui/icon.icns reaper.py"
  - "cd dist && ditto -c -k --sequesterRsrc --keepParent reaper.app reaper-macos.zip"
addons:
  artifacts: true
