language: python
os: osx
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      python: 3.5
    - os: osx
      osx_image: xcode8
      python: 3.5
python:
  - "3.5"
install: "pip install -r requirements.txt"
script:
  - "pip install pyinstaller"
  - pyinstaller -y --windowed --icon-ui/icon.icns reaper.py
  - cd dist && ditto -c -k --sequesterRsrc --keepParent reaper.app reaper-macos.zip
