os: osx
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      env: PYTHON=3.5.2
    - os: osx
      osx_image: xcode8
      env: PYTHON=3.5.2
script:
  - "brew update"
  - "brew install pyenv"
  - "pyenv"
  - env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.5.2
  - "pyenv local 3.5.2 && /Users/travis/.pyenv/versions/3.5.2/bin/python --version"
  - "/Users/travis/.pyenv/versions/3.5.2/bin/pip install --upgrade pip"
  - "/Users/travis/.pyenv/versions/3.5.2/bin/pip --version"
  - "/Users/travis/.pyenv/versions/3.5.2/bin/pip install socialreaper pyqt5 pyinstaller"
  - "/Users/travis/.pyenv/versions/3.5.2/bin/pyinstaller -y --windowed --icon=ui/icon.icns reaper.py"
  - "cd dist && ditto -c -k --sequesterRsrc --keepParent reaper.app reaper-macos.zip"
addons:
  artifacts: true
