environment:
  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x" # currently 3.5.3
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - cmd: "pip install --upgrade pip"
  - cmd: "pip install -r requirements.txt"
  - cmd: "pip install pyinstaller"

build_script:
  # Build the compiled extension
  - cmd: "pyinstaller reaper.py --windowed --icon=ui/icon.ico --add-data ui\\icon.png;ui"

# test_script:
#   # Run the project tests
#   - "%CMD_IN_ENV% python setup.py nosetests"
#
# after_test:
#   # If tests are successful, create binary packages for the project.
#   - "%CMD_IN_ENV% python setup.py bdist_wheel"
#   - "%CMD_IN_ENV% python setup.py bdist_wininst"
#   - "%CMD_IN_ENV% python setup.py bdist_msi"
#   - ps: "ls dist"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
#
